# -*- coding: utf-8 -*-
"""Streamlit.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-V2T97fWF9HCF3cOAKCENoo_fBnHGtRv
"""

!pip install yfinance
import streamlit as st
import yfinance as yf
import tensorflow as tf
import numpy as np
from tensorflow.keras.layers import LSTM, Dense, Dropout
from sklearn.model_selection import train_test_split
from sklearn.metrics import r2_score

st.title('Stock Price Prediction')

stock_symbol = st.text_input('Enter Stock Symbol', 'AAPL')

stock_symbol = st.text_input('Enter Stock Symbol', 'GOOG')

stock_symbol = st.text_input('Enter Stock Symbol', 'MSFT')

stock_symbol = st.text_input('Enter Stock Symbol', 'AMAN')

stock_symbol = st.text_input('Enter Stock Symbol', 'SATS')

if stock_symbol:
    stock_data = yf.download(stock_symbol, start='2020-01-01', end='2023-01-01')
    if not stock_data.empty:
        st.subheader('Stock Data')
        st.write(stock_data[['Open', 'High', 'Low', 'Close']]) # Pass a list of column names
    else:
        st.warning('No stock data available for the entered symbol.')
